version: '3.8'

services:
  flowchat-website:
    build: .
    ports:
      - "4000:3000"
    restart: unless-stopped
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3