# Production Docker Compose configuration for FlowChat static website
# Serves the static site using Nginx with custom configuration

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # Uncomment the next line if you plan to use SSL
      # - "443:443"
    volumes:
      # Mount the current directory to nginx html directory (read-only)
      - .:/usr/share/nginx/html:ro
      # Mount custom nginx configuration
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet

networks:
  webnet:
    driver: bridge